const TeamData = [
  {
    id: 1,
    img: "images/team/team1.svg",
    btn: "Advisory Board",
    linkedinLInk: "",
    logo: "/icons/nissan.svg",
    name: "Phil Clarke",
    specs: "Engine Specialist ",
    desc: "Modyfi co-founder and creative engineer Piers, has an interest in what can come from authentic.",
  },
  {
    id: 2,
    img: "images/team/team2.svg",
    btn: "Advisory Board",
    linkedinLInk: "",
    logo: "/icons/chevrolet.svg",
    name: "Phil Clarke",
    specs: "Auto Body Specialist",
    desc: "Modyfi co-founder and creative engineer Piers, has an interest in what can come from authentic.",
  },
  {
    id: 3,
    img: "images/team/team3.svg",
    btn: "Advisory Board",
    linkedinLInk: "",
    logo: "/icons/bmw.svg",
    name: "Ashleigh Penrod",
    specs: "Engine Specialist ",
    desc: "Modyfi co-founder and creative engineer Piers, has an interest in what can come from authentic.",
  },
  {
    id: 4,
    img: "images/team/team4.svg",
    btn: "Advisory Board",
    linkedinLInk: "",
    logo: "/icons/nissan.svg",
    name: "Papa Akuffo",
    specs: "Auto Body Specialist",
    desc: "Modyfi co-founder and creative engineer Piers, has an interest in what can come from authentic.",
  },
  {
    id: 5,
    img: "images/team/team1.svg",
    btn: "Advisory Board",
    linkedinLInk: "",
    logo: "/icons/nissan.svg",
    name: "Phil Clarke",
    specs: "Engine Specialist ",
    desc: "Modyfi co-founder and creative engineer Piers, has an interest in what can come from authentic.",
  },
  {
    id: 6,
    img: "images/team/team2.svg",
    btn: "Advisory Board",
    linkedinLInk: "",
    logo: "/icons/chevrolet.svg",
    name: "Phil Clarke",
    specs: "Auto Body Specialist",
    desc: "Modyfi co-founder and creative engineer Piers, has an interest in what can come from authentic.",
  },
  {
    id: 7,
    img: "images/team/team3.svg",
    btn: "Advisory Board",
    linkedinLInk: "",
    logo: "/icons/bmw.svg",
    name: "Ashleigh Penrod",
    specs: "Engine Specialist ",
    desc: "Modyfi co-founder and creative engineer Piers, has an interest in what can come from authentic.",
  },
  {
    id: 8,
    img: "images/team/team4.svg",
    btn: "Advisory Board",
    linkedinLInk: "",
    logo: "/icons/nissan.svg",
    name: "Papa Akuffo",
    specs: "Auto Body Specialist",
    desc: "Modyfi co-founder and creative engineer Piers, has an interest in what can come from authentic.",
  },
  {
    id: 9,
    img: "images/team/team1.svg",
    btn: "Advisory Board",
    linkedinLInk: "",
    logo: "/icons/nissan.svg",
    name: "Phil Clarke",
    specs: "Engine Specialist ",
    desc: "Modyfi co-founder and creative engineer Piers, has an interest in what can come from authentic.",
  },
  {
    id: 10,
    img: "images/team/team2.svg",
    btn: "Advisory Board",
    linkedinLInk: "",
    logo: "/icons/chevrolet.svg",
    name: "Phil Clarke",
    specs: "Auto Body Specialist",
    desc: "Modyfi co-founder and creative engineer Piers, has an interest in what can come from authentic.",
  },
  {
    id: 11,
    img: "images/team/team3.svg",
    btn: "Advisory Board",
    linkedinLInk: "",
    logo: "/icons/bmw.svg",
    name: "Ashleigh Penrod",
    specs: "Engine Specialist ",
    desc: "Modyfi co-founder and creative engineer Piers, has an interest in what can come from authentic.",
  },
  {
    id: 12,
    img: "images/team/team4.svg",
    btn: "Advisory Board",
    linkedinLInk: "",
    logo: "/icons/nissan.svg",
    name: "Papa Akuffo",
    specs: "Auto Body Specialist",
    desc: "Modyfi co-founder and creative engineer Piers, has an interest in what can come from authentic.",
  },
];

export default TeamData;
